services:
  nodejs-runner:
    build:
      context: .
      dockerfile: dockerfile.nodejs
      args:
        RUNNER_VERSION: '2.321.0'
    environment:
      - GITHUB_ORG=${GITHUB_ORG}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - LABELS=${LABELS_NODEJS}
    # volumes:
    #   - ./nodejs-runner:/home/actions-runner
    restart: always

  dotnet-runner:
    build:
      context: .
      dockerfile: dockerfile.dotnet
      args:
        RUNNER_VERSION: '2.321.0'
    environment:
      - GITHUB_ORG=${GITHUB_ORG}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - LABELS=${LABELS_DOTNET}
    # volumes:
    #   - ./dotnet-runner:/home/actions-runner
    restart: always

  multi-runner:
    build:
      context: .
      dockerfile: dockerfile.multi
      args:
        RUNNER_VERSION: '2.321.0'
    environment:
      - GITHUB_ORG=${GITHUB_ORG}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - LABELS=${LABELS_MULTI}
    # volumes:
    #   - ./multi-runner:/home/actions-runner
    restart: always
